from langchain_core.messages import ToolMessage
from langchain_core.tools import BaseTool

from app.agent.state import AgentState
from app.core.logging import get_logger

logger = get_logger(__name__)


async def tool_executor_node(state: AgentState, tools_by_name: dict[str, BaseTool]) -> dict:
    last_message = state["messages"][-1] #read that top message in state which will be AImessage object because this node runs after reasoner node in graph 
    tool_calls = last_message.tool_calls #check whether tool_calls is not empty 
    results = [] #this list will return ToolMessage ,empty now , filled later in this code 
    for tool_call in tool_calls:
        tool_name = tool_call["name"]#extracting name  from structured output generated by reasoner node 
        tool_input = tool_call["args"]#extracting args from structured output generated by reasoner node 
        tool_id = tool_call["id"]#extracting id from structured output generated by reasoner node 

        logger.info(f"Executing tool: {tool_name} | input: {tool_input}")

        tool: BaseTool = tools_by_name.get(tool_name)

        if not tool: #safety check 
            output = f"Tool '{tool_name}' not found."
        else:
            try:
               
                output = await tool.ainvoke(tool_input) 
                output = str(output)
            except Exception as e:
                output = f"Tool execution error: {str(e)}"
                logger.error(f"Tool {tool_name} failed: {str(e)}")

        logger.info(f"Tool {tool_name} result: {output[:100]}")

        results.append(
            ToolMessage(
                content=output,
                tool_call_id=tool_id,
            )
        )

    return {"messages": results} #append results to state 
 